const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const state = { connected:false, streaming:false, profile:'balanced', startTime:null, recording:{enabled:false,path:''}, video:{contrast:1,brightness:0,saturation:1,sharpness:.35,overlay:false}, destinations:[
  {name:'YouTube',icon:'▶',server:'rtmp://a.rtmp.youtube.com/live2/',enabled:false,key:'',status:'idle'},
  {name:'Twitch',icon:'◈',server:'rtmp://live.twitch.tv/app/',enabled:false,key:'',status:'idle'},
  {name:'Facebook',icon:'f',server:'rtmps://live-api-s.facebook.com:443/rtmp/',enabled:false,key:'',status:'idle'},
  {name:'TikTok',icon:'♪',server:'',enabled:false,key:'',status:'idle'}
]};
let timerInterval;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function camera(){return `http://${$('#printerIP').value.trim()}:3031/video`}
const statusLabel={idle:'En attente',connecting:'Connexion',live:'En direct',reconnecting:'Reconnexion',error:'Erreur'};
async function persistSecrets(){if($('#rememberKeys')?.checked)await window.centauri.saveSecrets(state.destinations)}
function renderDestinations(){
  $('#destinationList').innerHTML=state.destinations.map((d,i)=>`<article class="destination"><div class="desthead"><div class="destname"><div class="platformIcon">${d.icon}</div><div>${d.name}<p>${d.enabled?'Activée':'Désactivée'}</p></div></div><span class="destStatus ${d.status}">${statusLabel[d.status]||d.status}</span><button class="switch ${d.enabled?'on':''}" data-toggle="${i}"></button></div><div class="fields">${d.name==='TikTok'?`<input data-server="${i}" placeholder="URL du serveur RTMP TikTok" value="${esc(d.server)}">`:`<small>${d.server}</small>`}<input type="password" data-key="${i}" placeholder="Clé de diffusion" value="${esc(d.key)}"></div></article>`).join('');
  $$('[data-toggle]').forEach(b=>b.onclick=async()=>{state.destinations[+b.dataset.toggle].enabled=!state.destinations[+b.dataset.toggle].enabled;await persistSecrets();renderDestinations();updateReady()});
  $$('[data-key]').forEach(i=>i.onchange=async()=>{state.destinations[+i.dataset.key].key=i.value;await persistSecrets();updateReady()});
  $$('[data-server]').forEach(i=>i.onchange=async()=>{state.destinations[+i.dataset.server].server=i.value;await persistSecrets();updateReady()});
  updateReady();
}
function updateReady(){const active=state.destinations.filter(d=>d.enabled&&d.key&&d.server).length;const destinationStat=$('#statDest');if(destinationStat)destinationStat.textContent=`${active} active${active>1?'s':''}`;const outputReady=active>0||(state.recording.enabled&&state.recording.path);const ready=state.connected&&outputReady;$('#streamBtn').disabled=!ready&&!state.streaming;$('#readyDot').className='dot '+(ready?'ok':'');$('#readyText').textContent=ready?'Prêt à diffuser':'Configuration requise';$('#readyDetail').textContent=!state.connected?'Connectez une caméra':!outputReady?'Configurez une destination ou un enregistrement':'Tous les contrôles sont validés'}
async function connect(){const ip=$('#printerIP').value.trim();localStorage.setItem('printerIP',ip);$('#cameraLabel').textContent='Test de la connexion…';const result=await window.centauri.probe(ip);state.connected=result.camera;if(result.camera){$('#preview').src=camera()+`?t=${Date.now()}`;$('#preview').classList.add('connected');$('#emptyPreview').style.display='none';$('#cameraLabel').textContent=`Centauri Carbon · ${ip}:3031`;toast('Caméra connectée')}else{$('#preview').classList.remove('connected');$('#emptyPreview').style.display='grid';$('#cameraLabel').textContent='Caméra inaccessible';toast('Connexion impossible')}updateReady();return result}
$('#connectBtn').onclick=connect;$('#refreshPreview').onclick=()=>{if(state.connected)$('#preview').src=camera()+`?t=${Date.now()}`};
$('#discoverBtn').onclick=async()=>{const b=$('#discoverBtn');b.textContent='Détection en cours…';b.disabled=true;const found=await window.centauri.discover();$('#devices').innerHTML=found.length?found.map(d=>`<div class="device" data-ip="${d.ip}">Centauri Carbon — ${d.ip}</div>`).join(''):'<div class="device">Aucune imprimante trouvée</div>';$$('[data-ip]').forEach(x=>x.onclick=()=>{$('#printerIP').value=x.dataset.ip;connect()});b.textContent='⌕ Détecter automatiquement';b.disabled=false;toast(`${found.length} imprimante(s) détectée(s)`) };
$$('.profiles button').forEach(b=>b.onclick=()=>{$$('.profiles button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.profile=b.dataset.profile;localStorage.setItem('profile',state.profile);$('#statProfile').textContent=b.querySelector('span').textContent});
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.page).classList.add('active')});
$('#recordToggle').onclick=()=>{state.recording.enabled=!state.recording.enabled;$('#recordToggle').classList.toggle('on',state.recording.enabled);$('#recordToggle').setAttribute('aria-pressed',String(state.recording.enabled));updateReady();toast(state.recording.enabled?'Enregistrement local activé':'Enregistrement local désactivé')};
$('#chooseRecording').onclick=async()=>{const folder=await window.centauri.chooseRecordingFolder();if(folder){state.recording.path=folder;localStorage.setItem('recordingPath',folder);$('#recordingPath').textContent=folder;updateReady();toast('Dossier d’enregistrement sélectionné')}};
const imageDefaults={contrast:1,brightness:0,saturation:1,sharpness:.35};
function syncImageControls(){Object.keys(imageDefaults).forEach(key=>{$('#'+key).value=state.video[key];$('#'+key+'Value').textContent=Number(state.video[key]).toFixed(2)});$('#overlayToggle').classList.toggle('on',state.video.overlay)}
Object.keys(imageDefaults).forEach(key=>{$('#'+key).oninput=e=>{state.video[key]=Number(e.target.value);$('#'+key+'Value').textContent=state.video[key].toFixed(2);localStorage.setItem('videoSettings',JSON.stringify(state.video))}});
$('#overlayToggle').onclick=()=>{state.video.overlay=!state.video.overlay;$('#overlayToggle').classList.toggle('on',state.video.overlay);localStorage.setItem('videoSettings',JSON.stringify(state.video));toast(state.video.overlay?'Overlay ApeXploit activé':'Overlay ApeXploit désactivé')};
$('#resetImage').onclick=()=>{Object.assign(state.video,imageDefaults);syncImageControls();localStorage.setItem('videoSettings',JSON.stringify(state.video));toast('Réglages d’image réinitialisés')};
$('#streamBtn').onclick=async()=>{if(state.streaming){await window.centauri.stop();return}const result=await window.centauri.start({camera:camera(),profile:state.profile,destinations:state.destinations,recording:state.recording,video:state.video});if(!result.ok)return toast(result.error);setStreaming(true)};
function setStreaming(on){state.streaming=on;$('#streamBtn').textContent=on?'Arrêter le live':'Démarrer le live';$('#streamBtn').classList.toggle('stop',on);$('#liveBadge').innerHTML=on?'<span class="dot live"></span>EN DIRECT':'<span class="dot"></span>HORS LIGNE';$('#statState').textContent=on?'En direct':'En attente';if(on){state.startTime=Date.now();timerInterval=setInterval(()=>{const s=Math.floor((Date.now()-state.startTime)/1000);$('#timer').textContent=new Date(s*1000).toISOString().slice(11,19)},1000)}else{clearInterval(timerInterval);$('#timer').textContent='00:00:00';$('#statEncoding').textContent='— / —';$('#statSpeed').textContent='—'}updateReady()}
window.centauri.onEnded(code=>{setStreaming(false);toast(code===0?'Diffusion arrêtée':`Diffusion interrompue (code ${code})`)});
window.centauri.onDestinationState(({name,status})=>{const d=state.destinations.find(x=>x.name===name);if(d){d.status=status;renderDestinations()}});
window.centauri.onReconnecting(({attempt,delay})=>{state.streaming=true;$('#statState').textContent=`Reconnexion ${attempt}/5`;$('#liveBadge').innerHTML='<span class="dot"></span>RECONNEXION';toast(`Flux interrompu — nouvelle tentative dans ${Math.round(delay/1000)} s`)});
window.centauri.onReconnected(({attempt})=>{if(attempt){$('#statState').textContent='En direct';$('#liveBadge').innerHTML='<span class="dot live"></span>EN DIRECT';toast('Diffusion reconnectée automatiquement')}});
window.centauri.onRecordingStarted(path=>toast(`Enregistrement démarré : ${path.split(/[\\/]/).pop()}`));
window.centauri.onStats(({fps,bitrate,speed})=>{const targets={economy:'1,8 Mb/s cible',balanced:'3,5 Mb/s cible',studio:'5 Mb/s cible'};$('#statEncoding').textContent=`${fps} FPS / ${bitrate==='N/A'?targets[state.profile]:bitrate}`;$('#statSpeed').textContent=speed});
let logs='';window.centauri.onLog(text=>{logs=(logs+text).slice(-20000);$('#diagLog').textContent=logs;$('#diagLog').scrollTop=$('#diagLog').scrollHeight});
$('#runDiag').onclick=async()=>{const ip=$('#printerIP').value.trim(),p=await window.centauri.probe(ip),f=await window.centauri.ffmpegStatus();$('#diagLog').textContent=`Diagnostic Centauri Live\n\nImprimante : ${ip}\nCaméra (3031) : ${p.camera?'OK':'INACCESSIBLE'}\nContrôle (3030) : ${p.control?'OK':'INACCESSIBLE'}\nFFmpeg : ${f.installed?'INSTALLÉ':'ABSENT'}\nSystème : ${f.platform}\nFlux : http://${ip}:3031/video`};
$('#installFfmpeg').onclick=async()=>{const b=$('#installFfmpeg'),p=$('#installProgress');b.disabled=true;b.textContent='Installation en cours…';p.classList.add('active');$('#diagLog').textContent='Préparation de l’installation de FFmpeg…\n';const result=await window.centauri.installFfmpeg();if(!result.ok){b.disabled=false;b.textContent='Installer FFmpeg automatiquement';p.classList.remove('active');toast(result.error)}};
$$('[data-help]').forEach(button=>button.onclick=()=>window.centauri.openHelpLink(button.dataset.help));
window.centauri.onInstallLog(text=>{const log=$('#diagLog');log.textContent=(log.textContent+text).slice(-20000);log.scrollTop=log.scrollHeight});
window.centauri.onInstallEnded(async result=>{const b=$('#installFfmpeg'),p=$('#installProgress');p.classList.remove('active');b.disabled=false;b.textContent=result.ok?'FFmpeg installé ✓':'Réessayer l’installation';const status=await window.centauri.ffmpegStatus();$('#ffmpegDot').classList.toggle('ok',status.installed);$('#ffmpegText').textContent=status.installed?'Installé et prêt':'Installation requise';toast(result.ok?'FFmpeg est installé et prêt':`Échec de l’installation${result.code!==undefined?' (code '+result.code+')':''}`)});
window.centauri.ffmpegStatus().then(f=>{$('#ffmpegDot').classList.toggle('ok',f.installed);$('#ffmpegText').textContent=f.installed?'Installé et prêt':'Installation requise'});
async function initialize(){try{const savedIP=localStorage.getItem('printerIP');if(savedIP)$('#printerIP').value=savedIP;const savedProfile=localStorage.getItem('profile')||'balanced';state.profile=savedProfile;$$('.profiles button').forEach(b=>b.classList.toggle('selected',b.dataset.profile===savedProfile));const profileButton=$(`.profiles button[data-profile="${savedProfile}"]`);if(profileButton)$('#statProfile').textContent=profileButton.querySelector('span').textContent;try{state.recording.path=localStorage.getItem('recordingPath')||await window.centauri.defaultRecordingFolder()}catch{state.recording.path=''}$('#recordingPath').textContent=state.recording.path||'Choisissez un dossier';try{const secure=await window.centauri.secureStorageStatus();$('#rememberKeys').disabled=!secure.available;const saved=await window.centauri.loadSecrets();if(saved.ok&&saved.destinations.length){saved.destinations.forEach(s=>{const d=state.destinations.find(x=>x.name===s.name);if(d)Object.assign(d,{key:s.key||'',server:s.server||d.server,enabled:!!s.enabled})});$('#rememberKeys').checked=true}}catch{$('#rememberKeys').disabled=true}$('#rememberKeys').onchange=async()=>{if($('#rememberKeys').checked){await persistSecrets();toast('Clés enregistrées avec le chiffrement système')}else{await window.centauri.clearSecrets();toast('Clés enregistrées supprimées')}};renderDestinations();connect();initializeWizard()}catch(error){console.error('Initialization error',error);toast('Initialisation partielle : certaines options sont indisponibles')}}
function initializeWizard(){if(localStorage.getItem('onboardingDone'))return;const modal=$('#onboarding'),steps=[['Bienvenue dans Centauri Live','Configurons votre Centauri Carbon et le moteur vidéo en quelques instants.','Commencer'],['Détection de l’imprimante','Utilisez “Détecter automatiquement” pour retrouver la caméra même si son adresse IP change.','Continuer'],['Prêt à diffuser','Ajoutez une destination ou activez l’enregistrement local. Les clés peuvent être chiffrées par le système.','Terminer']];let step=0;modal.classList.add('show');const paint=()=>{$('#wizardStep').textContent=`ÉTAPE ${step+1} SUR ${steps.length}`;$('#wizardTitle').textContent=steps[step][0];$('#wizardText').textContent=steps[step][1];$('#wizardNext').textContent=steps[step][2]};const finish=()=>{localStorage.setItem('onboardingDone','1');modal.classList.remove('show')};$('#wizardSkip').onclick=finish;$('#wizardNext').onclick=()=>{if(step===1)$('#discoverBtn').click();if(++step>=steps.length)finish();else paint()};paint()}
try{const savedVideo=localStorage.getItem('videoSettings');if(savedVideo)Object.assign(state.video,JSON.parse(savedVideo))}catch{}
syncImageControls();
renderDestinations();
initialize();
